stages:
  - build
  - deploy
  - rollback

variables:
  REGISTRY: imgregistry.teresina.pi.gov.br
  IMAGE_NAME: $REGISTRY/$CI_PROJECT_NAME
  COMPOSE_DEV: docker-compose.dev.yml
  COMPOSE_HOM: docker-compose.hom.yml
  COMPOSE_PROD: docker-compose.prod.yml
  PROJECT_NAME_TRAEFIK: trp-eficiente-front
  APP_PORT: 3000

build_img:
  stage: build
  image: docker:latest
  tags:
    - homolog
  only:
    - homolog
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS $REGISTRY
  script:
    - export IMAGE_TAG=${CI_COMMIT_SHA}
    - docker build -t $IMAGE_NAME:$IMAGE_TAG -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - docker push $IMAGE_NAME:latest
  after_script:
    - docker logout


deploy_homolog:
  stage: deploy
  image: docker:latest
  tags:
    - homolog
  only:
    - homolog  
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS $REGISTRY
  script:
    - docker compose -f $COMPOSE_HOM pull
    - docker compose -f $COMPOSE_HOM up -d
    - docker image prune -f
  after_script:
    - docker logout
  environment:
    name: HOMOLOGACAO
    url: https://$URL_HOMOLOGACAO


rollback_homol:
  stage: rollback
  image: docker:latest
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS $REGISTRY
  script:
    - export IMAGE_NAME=$IMAGE_NAME:$CI_ROLLBACK_SHA
    - echo "Fazendo o rollback para a image $IMAGE_NAME"
    - docker compose -f $COMPOSE_HOM pull
    - docker compose -f $COMPOSE_HOM up -d
    - docker image prune -f
  after_script:
    - docker logout
  tags:
    - homolog
  only:
    - homolog
  when: manual
  environment:
    name: HOMOLOGACAO
    url: https://$URL_HOMOLOGACAO



deploy_prod:
  stage: deploy
  image: docker:latest
  tags:
    - prod
  only:
    - master  
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS $REGISTRY
  script:
    - docker compose -f $COMPOSE_PROD pull
    - docker compose -f $COMPOSE_PROD up -d
    - docker image prune -f
  after_script:
    - docker logout
  # dependencies:
  #   - build_img
  #   - deploy_homolog
  environment:
    name: PRODUCAO
    url: https://$URL_PRODUCAO

rollback_prod:
  stage: rollback
  image: docker:latest
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS $REGISTRY
  script:
    - export IMAGE_NAME=$IMAGE_NAME:$CI_ROLLBACK_SHA
    - echo "Fazendo o rollback para a image $IMAGE_NAME"
    - docker compose -f $COMPOSE_PROD pull
    - docker compose -f $COMPOSE_PROD up -d
    - docker image prune -f
  after_script:
    - docker logout
  tags:
    - prod
  only:
    - master
  when: manual
  environment:
    name: PRODUCAO
    url: https://$URL_PRODUCAO