version: '3.8'

services:
  transporte-eficiente:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - NODE_ENV=production
      - VITE_PUBLIC_API_URL=https://hom-api-transpef.teresina.pi.gov.br/api/v1/
      - VITE_GOOGLE_MAPS_API_KEY=AIzaSyCztfAw5XuwX85eK1WXFhsOlIX5iDxbGf8
    restart: always
    command: sh -c "serve -s dist -l ${APP_PORT}"